### ISSUE TITLE
Remove whitespace at top of html table in kml

### ISSUE THREAD

**Issue by ryanstocks00** [ANU-RE100/PHES_Searching#3]

**Comment by Anna-S-N** [comment]
Hi Ryan, the whitespace can be seen on the ArcGIS online maps, for example here: https://arcg.is/1PT0550

![image](https://user-images.githubusercontent.com/118416018/202353453-1b95e0ee-cf5c-486d-8214-4ebddbf613fb.png)

I tried altering the 500GWh kml and removing all / some of the formatting around the pop up table, but it seemed to either all be there or no formatting at all. 

In order to put these up on the web I always had to remove the <html> and <body> tags from the original kmls. This is what I would have removed on each reservoir:

<html>
              <head><META http-equiv="Content-Type" content="text/html"><meta http-equiv="content-type" content="text/html; charset=UTF-8"></head>
              <body style="margin:0px 0px 0px 0px;overflow:auto;background:#FFFFFF;">

**Comment by ryanstocks00** [comment]
Strange, there seem to be some extra new lines in the html that are causing the excessive spacing - any idea where these might be coming from? I don't think they're in the raw kml output.


![Image](https://user-images.githubusercontent.com/42725471/202364864-abbe58ec-d96a-4ca6-bf8b-0061d17356b2.png)

**Comment by Anna-S-N** [comment]
I hadn't seen those lines – is this from a kml that we created or one that
you downloaded from ArcGIS Online?

**Comment by Anna-S-N** [comment]
Can I ask what program you are using to open the kml?

**Comment by ryanstocks00** [comment]
Hmmm, that's just using inspect element in a web browser (so not looking at the raw kml, that's looking at the output from arcgis) - can you upload one of the bluefield kmls that was pu into arcgis?

**Comment by Anna-S-N** [comment]
I've put the edited kmls into this folder: https://www.dropbox.com/sh/72dpeahkqe6kfh2/AABm7gBdm5xDDl_w8lHQ0Hsqa?dl=0

**Comment by ryanstocks00** [comment]
They look fine, seems to be an issue with the upload to arcgis - is there any way I can test that out myself?

**Comment by Anna-S-N** [comment]
Sure – the username is anure100group, and the password is: NdseCYi2YrQY4Jm

**Comment by Anna-S-N** [comment]
I've put the edited kmls into this folder: https://www.dropbox.com/sh/72dpeahkqe6kfh2/AABm7gBdm5xDDl_w8lHQ0Hsqa?dl=0
